name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  push:
    # run when the workflow file is modified
    branches:
      - main
    paths:
      - ".github/youtube-cards.yml"
  # run when dispatched from actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: AgusSetiawn/github-readme-youtube-cards@main
        with:
          channel_id: UCmbefdA6ph8q_Fxy2D9hK0Q
          comment_tag_name: YOUTUBE-CARDS
          max_title_lines: 2
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
          output_type: html
